### PR TITLE
Travis CI: Switch deprecated `stable` NodeJS to `5` to test the latest 5.x.x NodeJS version

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ai** [comment]
But when nodejs will release new version, it will be automatically tested in Travis CI.

Mayb we should replace it to `latest` or something like it?

**Comment by ai** [comment]
Also do you have any links that `stable` was depreacted? I am curious.

**Comment by ntwb** [comment]
Yup, Travis needs to update there docs but here on the [NVM #Usage](https://github.com/creationix/nvm#usage) section of the docs its documented about the `stable` alias being deprecated.

In https://github.com/creationix/nvm/issues/870 there is a discussion about future aliases such as `LTS`, and other options...

That said though, the `4` and `5` here per the pull request just merged will use NVM to always test the latest 4.x.x (currently 4.2.4) and 5.x.x (currently 5.3.0) version/branches respectively so until NodeJS v6 is out things should be right here for a while :smirk:

**Comment by ai** [comment]
Seems like we can replace `stable` to `node`. `node` is a latest node release. What do you think about it?

**Comment by ntwb** [comment]
Another note, the previous Travis build [#1095](https://travis-ci.org/postcss/autoprefixer/jobs/98911334) using `stable` was testing NodeJS v5.2.0 rather than the current v5.3.0 that is now being tested

**Comment by ntwb** [comment]
On switching to `node` this also cause issues because Travis CI also use this an alias, Travis CI's alias here will be used before NVM's alias and as such using `node` will also test against NodeJS v5.2.0
, hence Travis need to update there docs surrounding all this.

You can see the `node` alias in action before and after the switch for `node-browserify` that I just submitted a pull request for also:
• https://travis-ci.org/substack/node-browserify/builds/98111654
• https://travis-ci.org/substack/node-browserify/builds/99246758

**Comment by ai** [comment]
Hm, seems like we have no good solution right now :'(.

**Comment by ai** [comment]
Can you also send same PR to [PostCSS](https://github.com/postcss/postcss). Autoprefixer is just a plugin and PostCSS core tests is more important.

**Comment by ntwb** [comment]
Thanks @ai, thought I had, but it was https://github.com/nDmitry/grunt-postcss/pull/78, will do right now :)

**Comment by ai** [comment]
`grunt-postcss`is just a small middleware between Grunt and PostCSS. PostCSS contains most of code.

**Comment by ntwb** [comment]
Done, and yes, I'm pretty familiar with all the PostCSS things :+1:

**Pull request merged**
