### PR TITLE
Code changes to ease the conversion to Deno

### PR DESCRIPTION
**Pull request by oscarotero**
Hi.
I've working on adding Deno support for autoprefixer, something similar to [postcss-deno](https://github.com/postcss/postcss-deno).

You can see the first version here: https://github.com/lumeland/autoprefixer-deno

I had to do some changes to the code to ease this conversion (CommonJS to ESM). These changes don't affect to the external API, it's just internal code changes.

Let me know if it's ok or you want me to make any change. Thanks!

### CODE REVIEW

**Comment by ai** [comment]
Can I ask to use `let` for variables to keep my code style?

**Comment by oscarotero** [comment]
No problem, It's done.

Out of curiosity, can I know the reason of using `let`?
`const` seems more appropiate if the variable won't be reassigned.

**Comment by ai** [comment]
> Out of curiosity, can I know the reason of using let?

I want to have a simple rule of choosing variable type ☺

**Comment by oscarotero** [comment]
Thanks!
I let you know when the Deno version is ready, in case you want to transfer the repository to postcss organization.

**Pull request merged**
