### PR TITLE
[css-grid] move media query cell placements to come after cell styles

### PR DESCRIPTION
**Pull request by yepninja**
Third solution without duplication media queries.

Now we have solutions for all [3 decisions](https://github.com/postcss/autoprefixer/issues/1048#issuecomment-390410054) that we discussed 😄

### CODE REVIEW

**Comment by ai** [comment]
Oh 😅

I prefer to duplicate medias. It is more stable for the cases (like 2-3 different media).

**Comment by yepninja** [comment]
[Here](https://github.com/postcss/autoprefixer/issues/1048) we decided to implement the solution without duplications.

**Comment by ai** [comment]
Since people afraid of Autoprefixer’s Grids, I think using safest way with a few extra media will be better to promotion.

They will be compressed by gzip and we need max safety.

cc @Dan503

**Comment by Dan503** [comment]
We agreed to do a half/half approach remember?

We don't want to shift author styles around in the declaration order. The goal is to create a single duplicate media query that holds all of the autoprefixer generated area code in it that is placed after the last grid area reference.

See my original example in the issue to see what I mean.

Creating a duplicate query for each area reference creates far too much code bloat and moving the full original media query is extremely dangerous.

**Comment by Dan503** [comment]
Option 2 is the method I'm talking about. That is the one we agreed to.

**Comment by ai** [comment]
@Dan503 but creating a single media for every area seems dangerous for me as well. Code bloat will be fixed by gzip. Are you sure that it is a good reason to not use the safest way?

**Comment by Dan503** [comment]
It's not every single one.

Take a good look at the example code I posted in the issue.

Notice that there is only one duplicate media query. There is not a duplicate for each declaration.

There is basically a duplicate query per media query per grid. It is not a duplicate query per query per area.

**Comment by ai** [comment]
> There is basically a duplicate query per media query per grid. It is not a duplicate query per query per area.

Yeap I got it. And I am afraid that combining different areas (which could be in different place of CSS file) into a that second media query is not safe, since we move areas declaration to a different position.

**Comment by Dan503** [comment]
Yes I know, Autoprefixer can't handle grids sharing the same area names. It has that restriction hard boiled into it's area code which is why I opened issue https://github.com/postcss/autoprefixer/issues/1038

I point this restriction out in the article and explain why it is the case so you won't need to worry about community backlash

**Comment by ai** [comment]
Released in 8.6.1

**Comment by Dan503** [comment]
I'll do the article updates tomorrow. Thanks for getting this over the line :D

**Pull request merged**
