### PR TITLE
Add `ms-writing-mode` value based on `direction` declaration

### PR DESCRIPTION
**Pull request by webschik**
Fix for #1152

### CODE REVIEW

**Comment by Dan503** [comment]
Thanks for doing this! 😁

One thing I'm worried about is that if IE11 is the only browser that needs to be supported, it won't output the prefixes since caniuse says IE11 doesn't need the -ms- prefixes.

Are you able to ensure that if IE11 is the only supported browser it still outputs the prefixes?

**Comment by webschik** [comment]
Hi @Dan503 !
I use this tool almost in all my projects, personal and at work, so I'm glad to help at least a little :)

Why will it not output the prefixes?

I checked Postcss v7.0.6 and autoprefixer v9.4.0, e.g. in this REPL https://autoprefixer.github.io, with the browser targets `last 2 version` and I've got the prefixed rule:

```
.example {
    writing-mode: vertical-rl;
}

.example {
    -webkit-writing-mode: vertical-rl;
        -ms-writing-mode: tb-rl;
            writing-mode: vertical-rl;
}
```

Caniuse and MDN say that IE has a partial support with depecated values `lr`, `lr-tb`, `rl`, `tb`, `tb-rl` (except for SVG support)

https://caniuse.com/#search=writing
https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

**Comment by Dan503** [comment]
> it won't output the prefixes since caniuse says IE11 doesn't need the -ms- prefixes.

IE11 doesn't understand the modern syntax but if you use the old syntax unprefixed, it will work in IE11. This means caniuse will say IE11 doesn't need prefixing. Due to it not supporting the modern syntax though, it does need prefixing.

That's what I'm worried about. `last 2 version` includes IE10 so it's not a valid test for this.

Assuming the browser target can be set without breaking other tests, set the browser target to just `ie 11` and check it still outputs prefixes.

**Comment by webschik** [comment]
@Dan503 , I see what you mean.

https://autoprefixer.github.io/, `ie >= 11`

```css
.example {
    writing-mode: vertical-rl;
}

.example {
    -ms-writing-mode: tb-rl;
            writing-mode: vertical-rl;
}
```

I've checked today your test cases from the issue in the real IE11 with the fixed values for `-ms-writing-mode`
and I've got the same result as in Chrome with `writing-mode`. So I see no problem if we use prefixed rule for IE instead of

```
.example {
    writing-mode: tb-rl;
    writing-mode: vertical-rl;
}
```

**Comment by Dan503** [comment]
Also you need to make a test for every iteration posted in the issue and check the output very carefully. Each type has very subtle differences between them.

You only have 4 tests but there are 6 different styles. Also I can tell that at least one of your tests is outputting incorrect values.

**Comment by webschik** [comment]
@Dan503 , but there were 3 cases for all values without specified `direction` (so I treat them as `direction: ltr`), I've added new cases for `horizontal-tb`, `vertical-rl`, `vertical-lr` with `direction: rtl`

**Comment by Dan503** [comment]
Ok i did a bit of my own testing, the prefixes do seem to be getting applied even if IE11 is the only browser that needs supporting so that's good.

There is still a need to fix your tests though before this can be merged.

**Comment by Dan503** [comment]
In the [original issue](https://github.com/postcss/autoprefixer/issues/1152), look under the "Examples of every combination" heading. There are 6 different styles there that all need to be tested for. They are all slightly different from one another.

**Comment by webschik** [comment]
"Modern" `writing-mode` has 3 values that relate on `direction ltr/rtl` in IE:
```css
writing-mode: horizontal-tb;
writing-mode: vertical-rl;
writing-mode: vertical-lr;
```

So, there are 6 possible cases (3 for each direction):

```css
.one {
    writing-mode: horizontal-tb;
    /* optional direction: ltr; */
}

.two {
    writing-mode: horizontal-tb;
    direction: rtl;
}

.three {
    writing-mode: vertical-rl;
    /* optional direction: ltr; */
}

.four {
    writing-mode: vertical-rl;
    direction: rtl;
}

.five {
    writing-mode: vertical-lr;
    /* optional direction: ltr; */
}

.six {
    writing-mode: vertical-lr;
    direction: rtl;
}
```

we have all of them in [test/cases/writing-mode.css](https://github.com/webschik/autoprefixer/blob/ms-writing-mode/test/cases/writing-mode.css)

**Comment by Dan503** [comment]
I'm actually at the coast. I was going to come home tonight but I'm staying an extra night.

**Comment by ai** [comment]
Released in 9.4.4

**Pull request merged**
