### PR TITLE
Fix ::file-selector-button pseudo-element

### PR DESCRIPTION
**Pull request by usmanyunusov**
https://twitter.com/usmanyunusov

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ai I think this introduced `::-moz-file-selector-button` which is invalid/never implemented.

**Comment by ai** [comment]
@XhmikosR can you send PR to block usage of `-moz-`?

**Comment by XhmikosR** [comment]
Unsure where to look for, I'm not familiar with the codebase :/

**Comment by ai** [comment]
@usmanyunusov can you add text for Firefox and prevent wrong prefix generation?

**Comment by usmanyunusov** [comment]
@ai, I'll see the error

**Pull request merged**
