### PR TITLE
Add a FAQ section for IE grid support caveats

### PR DESCRIPTION
**Pull request by CyberAP**
See: https://github.com/postcss/autoprefixer/issues/1074

### CODE REVIEW

**Comment by ai** [comment]
Good idea. Let's just add free code examples and link to that CSS Trick article.

**Comment by ai** [comment]
I improve this FAQ section 83cbac7

WHat do you think?

**Comment by CyberAP** [comment]
Seems reasonable. But I'd still add an example with no `grid-template*` or `grid-area` set, using only manual grid item assignment. Like this:
```css
.grid
{
  display: grid;
}

.grid > :nth-child(1)
{
  grid-column: 1;
  grid-row: 1;
}

.grid > :nth-child(2)
{
  grid-area: 1 / 2; /* Shorthand for grid-row and grid-column */
}
```

**Comment by ai** [comment]
Why do you like to avoid `grid-template`? It is more readable in my opinion.

**Comment by CyberAP** [comment]
To show that it is not required here and it can work out of the box without it. The only thing that has to be done is grid item assignment.

**Comment by ai** [comment]
In the new section, I cover a little more than just Grid with a missed position. Also, I am not sure that `:nth-child(1)` and `grid-column/row` is the best practice to promote it. It is better to promote BEM selectors and readable position.

**Pull request merged**
