### PR TITLE
Replace initClass() to static propeties

### LINKED ISSUE #816: Replace initClass() to static propeties
Right now we use `initClass()` method to set static properties to class. But Babel support spec draft for static properties and we should use it as PostCSS.

@Semigradsky do you want to finish your CoffeeScript → ES7 migration?

### PR DESCRIPTION
**Pull request by Semigradsky**
Fixed #816

### CODE REVIEW

**Comment by ai** [comment]
Great.You are fast.

But you need to update `yarn.lock` file too. This project uses `yarn` instead of slow `npm`.

**Comment by Semigradsky** [comment]
Updated

**Comment by ai** [comment]
Thanks

**Comment by Semigradsky** [comment]
It's strange. I not see this changes in v7 branch.
Was it reverted?

**Comment by ai** [comment]
Strange too. Maybe I override it on rebase. I will pull it again. Thanks for noticing.

**Pull request merged**
