### PR TITLE
ymo

### PR DESCRIPTION
**Pull request by shinnn**

### CODE REVIEW

**Comment by MoOx** [comment]
wtf?

**Comment by MoOx** [comment]
Are you lost in Vim?

**Comment by dascritch** [comment]
$ cat on the keyboard

**Comment by shinnn** [comment]
Oooooooooooouch. I tested something but I mistook the target repo of PR. Sorry!

**Comment by HugoGiraudel** [comment]
WTF

**Comment by ai** [comment]
:-D

**Pull request closed without merging**
