### PR TITLE
Refactoring, delete unnecessary else

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ai: are you sure this was right? I'm seeing `webkit-box-align` when before I didn't.

**Comment by ai** [comment]
@XhmikosR send PR with a test and reverting this commit

**Comment by XhmikosR** [comment]
@ai I'm not familiar with the codebase, so maybe this wasn't the root cause. I'll make an issue, but going back to 9.1.5 I don't get the `-webkit-box-align` being added.

**Comment by ai** [comment]
@XhmikosR in this case with send PR with a test, which was passed in 9.1.5 and will not be passed in 9.2.

**Pull request merged**
