### PR TITLE
Look for outdated gradient syntax only inside radial-gradient block

### LINKED ISSUE #1015: Incorrect "outdated gradient" warning on `background` shorthand
Hi,

This input returns an incorrect warning:

```css
a { background: radial-gradient(#FFF, transparent) 0 0 / cover no-repeat #F0F; }
```

The error:

> 2:2	⚠  Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`. [autoprefixer]

In this context, `cover` is used as the `background-size`, not the `radial-gradient` direction.

### PR DESCRIPTION
**Pull request by kotfire**
Fixes #1015

### CODE REVIEW

**Comment by ai** [comment]
Thanks! I will release it with #1018

**Comment by radium-v** [comment]
Does this account for multiple background images in a shorthand?

```css
a {
	background: linear-gradient(#F0F, #000), radial-gradient(0 0, cover, #FFF, transparent) 0 0 / cover no-repeat #F0F;
}
```

**Comment by ai** [comment]
@radium-v

**Comment by ai** [comment]
@radium-v can you try? Just clone repo and add the test (also send PR with this test).

I am going to speak on meetup. Don't have time today.

**Comment by radium-v** [comment]
Yes, I want to address this issue and dive deeper into it, I'm just waiting for some free time this weekend ;)

**Comment by ai** [comment]
@radium-v I tested. Everything is fine 54fa0ac

**Comment by ai** [comment]
Released in 8.3.

**Pull request merged**
