### PR TITLE
Show warning if grid-area has a non-unique identifier (fixes #1038)

### LINKED ISSUE #1038: [css-grid] Report a warning if duplicate area names are detected
Take this css:

````css
.grid-alpha {
  grid-template-areas: "delta  echo";
}

.grid-beta {
  grid-template-areas: "echo  delta";
}

.grid-cell {
  -ms-grid-column: ???; /* what column does .grid-cell go in? */
  arid-area: echo;
}
````

Autoprefixer has no access to the DOM so it doesn't really know what area `.grid-cell` belongs to.

Currently Autoprefixer silently just goes with whatever the last `grid-template-areas` definition was in the style-sheet (in this case `"echo  delta"`). If a user places `.grid-cell` in `.grid-alpha` then it will look great in modern browsers but be placed in the wrong column in IE.

Since it is silent, a user could end up building their whole site blissfully unaware of this issue, using duplicate area names everywhere, then finally open IE to see their whole layout go to shit.

Autoprefixer should detect if there are any area name conflicts and if so, warn users to use unique area names at all times.

### PR DESCRIPTION
**Pull request by bogdan0083**
This is my first PR which adds warning when grid-area has a non-unique identifier (conflict of names). #1038

Not sure if code is clean enough, but I had a lot of fun working on this issue. Thanks! :)

Some questions:
* In my code I refer to area names in grid-area as "identifiers" ([see this](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)). Is it alright?
* How should we handle grid-area inside media? I've omitted checking warnings inside media for now

### CODE REVIEW

**Comment by ai** [comment]
Hi. The code is great.

But `grid-template.css` doesn’t have name conflicts ;).

We must find when different tags use the same name in `grid-area`, not when different parents use the same area in `grid-template`.

But the fix should be fast :).

**Comment by ai** [comment]
The code is great :+1: 

@Dan503 @yepninja what do you think?

**Comment by ai** [comment]
@bogdan0083 why it doesn’t see name conflict between `.c` and `.hd`?

**Comment by Dan503** [comment]
I'll take a close look at this tonight to see if it works how I expect it to.

**Comment by ai** [comment]
Yeap, it is my mistake :(. There are no problems right now. Great work.

Let’s wait @Dan503 review (anyway I want to wait for #1081 before releasing it).

**Comment by Dan503** [comment]
... ummm... ok I'm stumped.

How exactly do I go about testing this pull request? 😕

**Comment by bogdan0083** [comment]
Whoops. I've just pushed a commit. Did I break something?

**Comment by Dan503** [comment]
No, (or well I don't know) I just don't know how to test :P

**Comment by bogdan0083** [comment]
Alright. In the last commit I've added warning for a grid-area even inside media rules. It should trigger inside a media in the following cases: 

* If we're can't find the same selector outside media
* If we found the same selector, but outside grid-area value is different

In all other cases a warning will not be shown.

**Comment by Dan503** [comment]
I've taken a look at your test cases file. It is missing media query tests. It is also missing comma separated list tests.

````css
/* Your current tests */
.g {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "g   g" 100px
        "g   g" 100px
        "h   h" 100px /
        1fr  1fr;
}

.g-conflict {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "g   g" 100px
        "g   g" 100px
        "h   h" 100px /
        1fr  1fr;
}

@media (min-width: 600px) {
  /* This should *not* trigger a warning */
  .g {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "g   h" 100px /
        1fr  1fr;
  }

  /* This *should* trigger a warning */
  .g-conflict-2 {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "g   h" 100px /
        1fr  1fr;
  }
}

/* comma list tests */
/* None of these should throw any warnings (unless specified) */
.i, .j {
  display: grid;
  grid-gap: 10px;
  grid-template:
      "i    j" 100px /
      1fr  1fr;
}

@media (max-width: 600px) {
  .i {
    grid-template:
      "i" 100px
      "j" 100px /
      1fr;
  }
  .j {
    grid-template:
      "i" 100px
      "j" 100px /
      1fr;
  }

  /* This one should throw a warning */
  .k {
    grid-template:
      "i" 100px
      "j" 100px /
      1fr;
  }
}

@media (min-width: 900px) {
  .i, .j {
    display: grid;
    grid-gap: 10px;
    grid-template:
      "i" 100px
      "j" 100px /
      1fr;
  }
}

/* media query test */
@media (min-width: 601px) {
  .l {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "l   m" 100px /
        1fr  1fr;
  }
}
@media (max-width: 600px) {
  .l {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "l   m" 100px /
        1fr  1fr;
  }

  /* this should display a warning */
  .z {
    display: grid;
    grid-gap: 10px;
    grid-template:
        "m   z" 100px /
        1fr  1fr;
  }
}
````

That's all the tests I can think of.

**Comment by bogdan0083** [comment]
Alright, thanks! Looks like I choose a completely wrong approach. I triggered warning only when grid-area is used (which is not very good as I understood now). 

Now I'll just take your code above as test case and show warnings every time there are duplicate area names 👍

**Comment by Dan503** [comment]
> I triggered warning only when grid-area is used  (which is not very good as I understood now).

Having `display: grid;` in the same rule should not be a requirement for the warning to not go off. It should still be powered pretty much entirely through the `grid-template-areas` property if possible.

**Comment by Dan503** [comment]
Yeah the media query and comma seperated list support is what makes this issue much more difficult to fix than it appears to be on the surface.

**Comment by bogdan0083** [comment]
Alright, looks like now it should work as expected inside media rules now 😄 

@Dan503 Can you please check the last commit in your spare time please? These are the warnings I have from the last grid-template.css:
```
"autoprefixer: <css input>:41:5: duplicate area names: head, nav, main, foot",
"autoprefixer: <css input>:133:5: duplicate area names: g, h",
"autoprefixer: <css input>:154:5: duplicate area names: g, h",
"autoprefixer: <css input>:186:5: duplicate area names: i, j",
"autoprefixer: <css input>:228:5: duplicate area name: m",
``` 

And then we can go for a code review! :)

**Comment by Dan503** [comment]
If those are the warnings that those test are giving off now then that sounds like it's working how it's supposed to :)

I feel like the warning message isn't detailed enough though. It warns that duplicate area names are used but it doesn't tell users why duplicate area names are bad or what CSS selector is causing the issue.

If the warning could say something more like this then I think it would be better:

````
autoprefixer: <css input>:41:5:
duplicate area names detected in rule: .g-conflict
duplicate area names: g, h
Duplicate area names cause unexpected behavior in IE
````

**Comment by Dan503** [comment]
You can use `\n` to create the line breaks, or template literals if ES6 is an option.

**Comment by bogdan0083** [comment]
Alright, done 👍 

@ai Now we can review the code I guess (or we can wait until #1081 is fixed, doesn't matter). I changed the implementation completely compared to the initial commit.

**Comment by Dan503** [comment]
I just took a look at the commit. You are using one big template literal which is ok but you need to factor in prefered output white space rather than whatever whitespace lines up nicely with the rest of the code in the file.

The warning will currently be outputting this:
````
autoprefixer: <css input>:133:5: 
        duplicate area names detected in rule: .g-conflict
        duplicate area names: g, h
        duplicate area names cause unexpected behavior in IE
````

A bit of an indent is ok but 8 spaces worth is a bit much :/

A large indent will cause it to go off the screen or wrap in peoples console windows earlier than it needs to.

I'd recommend reducing the indent down to 2 spaces.
````
autoprefixer: <css input>:133:5: 
  duplicate area names detected in rule: .g-conflict
  duplicate area names: g, h
  duplicate area names cause unexpected behavior in IE
````

**Comment by bogdan0083** [comment]
> I just took a look at the commit. You are using one big template literal which is ok but you need to factor in prefered output white space rather than whatever whitespace lines up nicely with the rest of the code in the file.

I've been aware of this issue and I thought maybe someone would give me an advice on fixing the indentation (but forgot to ask).

In the code I use a postcss ```warn``` method to show a warning:
```js
      decl.warn(
        result,
        `
        duplicate area ${ word } detected in rule: ${ rule.selector }
        duplicate area ${ word }: ${ duplicates.join(', ') }
        duplicate area names cause unexpected behavior in IE`
      )
```

the part ```autoprefixer: <css input>:133:5:``` adds automatically before the string.

If I want to indent warning normally, I have to format a warning method like this:
```js
       decl.warn(
        result,
        `
     duplicate area ${ word } detected in rule: ${ rule.selector }
     duplicate area ${ word }: ${ duplicates.join(', ') }
     duplicate area names cause unexpected behavior in IE`
      ) 
```
which is quite an ugly way to indent code.
And the same for the testing code. 

If I use normal string like ```'string' + '\n'``` it still breaks the indentation. 

I searched every warning inside autorefixer – they all are one-liners. I even checked the testing code for warn method (in postcss repository) – there are no multi-line warnings in there as well.

I guess we need to wait what Andrey says on how to fix this (or someone who knows how to make warnings multi-line).

**Comment by bogdan0083** [comment]
> If you don't want to deal with the ugliness, try this instead. It should produce the output with a 2 space indent. 

Thank you very much! Such a simple solution! :smile:

**Comment by ai** [comment]
Are we ready for merge and everything was fixed in the last commit?

**Comment by bogdan0083** [comment]
@ai yep, I finished working on this PR. If code is fine we can merge.

**Comment by Dan503** [comment]
Yep, I'm happy for it to be merged :)

**Comment by ai** [comment]
Released in 9.0.2

**Comment by ShaggyDude** [comment]
This is amazing work. Thank you all!

**Pull request merged**
