### PR TITLE
Porting to JavaScript

### PR DESCRIPTION
**Pull request by Semigradsky**
#810

⚠️ ~~Not ready for merge yet.~~

After third commit performance was ruined. Now it's more than 20x times slower.

I will investigate and update PR.

### CODE REVIEW

**Comment by ai** [comment]
Can you send it again to `v7` branch?

**Comment by Semigradsky** [comment]
Speed has been restored. On my PC:
```
[13:01:36] Using gulpfile D:\github\benchmark\gulpfile.js
[13:01:36] Starting 'bootstrap'...
[13:01:36] Finished 'bootstrap' after 331 μs
[13:01:36] Starting 'prefixers'...
[13:01:37] Running suite Bootstrap [D:\github\benchmark\prefixers.js]...
[13:01:43]    Autoprefixer dev x 15.36 ops/sec ±11.01% (51 runs sampled)
[13:01:49]    Autoprefixer x 16.07 ops/sec ±10.66% (53 runs sampled)
[13:01:49] Fastest test is Autoprefixer at 1.05x faster than Autoprefixer dev

Autoprefixer:     62 ms
Autoprefixer dev: 65 ms (1.0 times slower)
```

**Comment by ai** [comment]
Great! What else do we need to do before merge?

**Comment by Semigradsky** [comment]
I think it's ready to merge.

**Comment by lydell** [comment]
@Semigradsky Did you find why the 20x slowdown happened? I'm super curious! :)

**Comment by ai** [comment]
OK, I will try to look on this week

**Comment by Semigradsky** [comment]
@lydell this line:
https://github.com/postcss/autoprefixer/pull/812/commits/f67569e5606bec15d13033fd8b227be1f66b986f#diff-1ea033eede7961e81fac67f7cf52fd51R316

At first I changed this line to `if (node._autoprefixerDisabled) {`.
It ruined performance.

**Comment by ai** [comment]
You forget to fix `data/` and `test/` :'(

**Pull request merged**
