### PR TITLE
Add missing space in `autoprefixer -info` CLI docs

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ai** [comment]
Nope. It is a special `autoprefixer-info` tool. It has this name to avoid conflict with `autoprefixer-cli` bin and because `autoprefixer-info` doesn't add prefixes.

**Comment by ntwb** [comment]
Running `npx autoprefixer-info` (without the space) results in:

```shell
npm ERR! code E404
npm ERR! 404 Not Found: autoprefixer-info@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/netweb/.npm/_logs/2018-01-30T06_19_26_377Z-debug.log
Install for autoprefixer-info@latest failed with code 1
```

Running `npx autoprefixer -info` (with the space) results in:

```
npx: installed 17 in 2.307s
Browsers:
  Chrome for Android: 62
  Firefox for Android: 57
  And_qq: 1.2
  UC for Android: 11.4
  Android: 62, 4.4.3-4.4.4
  Baidu: 7.12
  Bb: 10, 7
  Chrome: 63, 62
  Edge: 16, 15
  Firefox: 57, 56, 52
  IE: 11, 10
  IE Mobile: 11, 10
  iOS: 11.0-11.2, 10.3
  Opera Mini: all
  Opera Mobile: 37, 12.1
  Opera: 49, 48
  Safari: 11, 10.1
  Samsung: 6.2, 5, 4

These browsers account for 88.33% of all users globally
...
...
...
```

I think `npx` has some _smarts_ on detecting which command parameters to pass to the called package and that is why it works maybe?

**Comment by ai** [comment]
Yeap. You need to install `autoprefixer` first.

Look at repository, there is no `autoprefixer` CLI here. `npx autoprefixer -info` install different package.

**Comment by ntwb** [comment]
`npx` doesn't use installed packages, it *always* installs from the npmjs.com registry.

After installing `autoprefixer` globally I have to run `autoprefixer-info` (no space, also no `npx`)

To run it via `npx` it must be a valid package on npmjs.org, https://www.npmjs.com/package/autoprefixer-info is *not* a valid package.

**Comment by ai** [comment]
Can you execute `./node_modules/.bin/autoprefixer-info`?

**Comment by ai** [comment]
Seems like both of our solution is wrong. And we need to find different one.

What Autoprefixer version do you have in the project?

Maybe I could rename CLI tool to `autoprefixer` to work `npx` correctly.

**Comment by ntwb** [comment]
Yes, that works perfectly using v7.2.5

```shell
./node_modules/.bin/autoprefixer-info 
Browsers:
  Chrome for Android: 62
  Firefox for Android: 57
...
...
```

**Comment by ntwb** [comment]
Here is what this PR should do after reading the `npx` docs: 
• https://www.npmjs.com/package/npx#description

`npx autoprefixer-info --package autoprefixer` where:
• `autoprefixer-info` <- is the _command_ `npx` will run
• `--package autoprefixer` <- is the _package_ that `npx` installs to run the above _commad_

**Comment by ai** [comment]
Awesome. Will you update be PR?

**Comment by ntwb** [comment]
Done in https://github.com/postcss/autoprefixer/pull/978/commits/eb844564798b8251e0cc558a9798860853270439

**Comment by ntwb** [comment]
Also the following needs updating: https://github.com/postcss/autoprefixer#cli

Currently:
```
npm install postcss-cli autoprefixer
npx postcss *.css --use autoprefixer -d build/
```

It should be:
```
npm install postcss-cli autoprefixer
./node_modules/.bin/postcss *.css --use autoprefixer -d build/
```

Or it should be:
```
npx postcss *.css --use autoprefixer -d build/ --package autoprefixer postcss-cli
```

Which one do you want in a follow up PR @ai ?

**Comment by ai** [comment]
Nope. It is longer and everything works in clients.

**Comment by ai** [comment]
In next 8.0 CLI will be renamed to `autoprefixer` https://github.com/postcss/autoprefixer/issues/985

**Pull request merged**
