### PR TITLE
Augment prefixes data with feature name

### PR DESCRIPTION
**Pull request by cvle**
As discussed in https://github.com/postcss/autoprefixer/issues/754, this PR exposes the feature name in the prefixes data.

### CODE REVIEW

**Comment by ai** [comment]
Could I release it in Monday? I need to fix something in PostCSS.

**Comment by cvle** [comment]
Sure, thanks a lot!

**Comment by ai** [comment]
There is no Can I Use update. I will release it with next Can I Use update. Is it OK?

**Comment by cvle** [comment]
Yes that's alright. I'll just continue to work with my local fork until then.

**Comment by ai** [comment]
Released in 6.6.1.

**Comment by cvle** [comment]
Great 👍

**Pull request merged**
