### PR TITLE
Remove flex-flow hack

### PR DESCRIPTION
**Pull request by jrowlingson**
Fixes https://github.com/postcss/autoprefixer/issues/776

### CODE REVIEW

**Comment by ai** [comment]
Nice try :D. You broke the tests ;).

You need to fix it without test changes.

**Comment by ai** [comment]
I added this hack to fix prefixes removing. We can’t just remove hack, because in this case Autoprefixer will not be able to remove prefixes.

**Comment by jrowlingson** [comment]
Ah thanks for taking a look :)


Correct me if I am wrong, but, if I am thinking about the fix correctly we will specifically want to retain the `-webkit-box-orient` declaration when present - so I would still need to change the tests for this case.

**Comment by ai** [comment]
Why we should keep `-webkit-box-orient`?

Let’s me explain Flexbox tests:

1. Test that prefixes added correctly: `flexbox.css` → AP → `flexbox.out.css`
2. Test that we remove all prefixes: `flexbox.out.css` → AP(`browsers: []`) → `flexbox.css`
3. Test that we do not double prefixes: `flexbox.css` → AP → AP → `flexbox.out.css`
4. Test that we can disable flexbox: `flexbox.out.css` → AP(`flexbox: false`) → `flexbox.css`

I added `notHack = true if unprefixed == 'flex-flow'` to fix test number 2.

Autoprefixer try to find a groups:

```css
.foo {
  -webkit-box-shadow: x;
  box-shadow: x
}
```

If he didn’t find a unprefixed (`box-shadow`) version in group, it decide that it is the “hack”, and should not be removed.

Unfortunately, in this case we need 2-3 different prefixed properties:

```css
.foo {
  -webkit-box-orient: horizontal;
    -webkit-box-direction: reverse;
            flex-direction: row-reverse;
}
```

Because `box-direction` is not equal to `flex-direction, Autoprefixer decide, that `-webkit-box-direction` is a hack (prefix without unprefixed version near by). So removing test was broken.

This is why I remove hack detection logic for this case (honestly, because I gave up, logic became too complicated here, Autoprefixer should not be perfect in any case).

**Comment by jrowlingson** [comment]
Thanks for the explanation; the behavior the tests are asserting is clear to me now. I see that the tests should not need to change here.

> Why we should keep -webkit-box-orient?

The original issue is that there are valid cases where the `-webkit-box-orient` is used as a hack so removing it causes the layout to break. For example, when used as a [line clamp](https://css-tricks.com/line-clampin/#article-header-id-0): 

```css
.line-clamp {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;  
}
```

But I can see the hack detection logic needed here is non-trivial. I might take another pass at detecting this case if you think its worth it.

**Comment by jamesbrobb** [comment]
I have the same use case for  `-webkit-box-orient: vertical;, so am also now experiencing issues with broken layouts, due to the removal.

**Comment by ai** [comment]
@jamesbrobb could you show you more of your CSS?

**Comment by jamesbrobb** [comment]
Apologises, i thought i was running the latest version of chrome, in which the following css still worked:
```
{
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: horizontal;
}
```
But have just updated to  `56.0.2924.87` and see that these styles are no longer valid.

**Comment by jamesbrobb** [comment]
Sorry, my mistake again, i was testing and hadn't noticed i had `horizontal` instead of `vertical`.

This still works in the latest version of chrome and as i'm using 'last 2 versions' shouldn't it still be supported and therefore not removed?

.clamp-text {
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}

**Comment by ai** [comment]
Nope, `-webkit-` prefixes is not required for `last 2 version` http://caniuse.com/#search=flexbox

**Comment by ai** [comment]
Also I highly recommend to refector this code and replace `display: -webkit-box` to `display: flex`.

You have a Autoprefixer for prefixes, manually written prefixes is a bad practices. Prefixes for only one browsers is not really moral thing ;). Prefixes without unprefixed version is not future-proof — Chrome will disable `-webkit-box` in some future and you code will be broken.

**Comment by romulof** [comment]
`-webkit-line-clamp` only works with `-webkit-box`

**Comment by domschmidt** [comment]
We're using line clambing if the browser supports it, e.g. as follows:

```
  @supports (-webkit-line-clamp: 1) {
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
  }
```

As a result, -webkit-box-orient: vertical; is removed at all

**Comment by ai** [comment]
Disable Autoprefixer here by control comments or use `remove: false` option.

**Comment by domschmidt** [comment]
Works fine, thank you

**Comment by RVNranjan** [comment]
@ai im using gulp/grunt inside node_modules\autoprefixer\node_modules\postcss\lib , i have postcss.js but not postcssrc.js

**Comment by ai** [comment]
@RVNranjan show your config for gulp

**Comment by RVNranjan** [comment]
@ai 

'use strict';

var gulp   = require('gulp'),
    help   = require('gulp-help')(gulp),
    config = require('./lib')(gulp, { help: true });

// ===================
// CONFIG
// ===================

config({

    paths: {
        source: ['./lib/**/*.js', './tasks/**/*.js'],
        tests : ['./test/**/*.js']
    },

    // tasks
    // ------------------------

    jshint  : { lint : '<%=paths.source%>' },
    mocha   : { specs: '<%=paths.tests%>'  }

});

gulp.task('test', ['jshint', 'mocha']);

**Comment by ai** [comment]
@RVNranjan do you already have Autoprefixer in your project? Or you all me how to add it?

**Comment by RVNranjan** [comment]
I already have that

**Comment by RVNranjan** [comment]
@ai I already have Autoprefixer in my project, just i want to know how to do Autoprefixer return: false.

**Comment by ai** [comment]
@RVNranjan OK, where did you enable the Autoprefixer?

In Grunt config? Or you use it as text editor plugin?

**Comment by RVNranjan** [comment]
@ai autoprefixer is enabled in Grunt config

**Comment by ai** [comment]
@RVNranjan awesome! :) show a config and I will tell where exactly you need to change it :)

**Pull request closed without merging**
