### PR TITLE
fix Processor.disabled(): check if node has parent before get prev()

### PR DESCRIPTION
**Pull request by Diablohu**
If not do so, there are fatal errors, at least on my projects...

### CODE REVIEW

**Comment by ai** [comment]
Strange. This issue was fixed in latest PostCSS release 6.0.22.

**Comment by ai** [comment]
@Diablohu you got this error after `npm update`?

**Comment by ai** [comment]
Released in 8.4.1

**Comment by Diablohu** [comment]
I now know what cause this. You are right that PostCSS v6.0.22 fixed this. But `postcss-loader` dose not update yet...

**Pull request merged**
