### PR TITLE
Can't find browserslist config from browserslist config file or packa…

### PR DESCRIPTION
**Pull request by ken1987**
My english is poor，I'll give some code and comment to describe the question

## step1: [autoprefixer/lib/autoprefixer.js#L81](https://github.com/postcss/autoprefixer/blob/f37e5ba9cff5c2d4429306b3f0562f130c7b6d6c/lib/autoprefixer.js#L81)

```
const plugin = function (css, result) {
        const prefixes = loadPrefixes({
            // sometimes `css.source && css.source.input.file === undefined`
            from: css.source && css.source.input.file,  
            env: options.env
        });
        timeCapsule(result, prefixes);
        if (options.remove !== false) {
            prefixes.processor.remove(css, result);
        }
        if (options.add !== false) {
            prefixes.processor.add(css, result);
        }
    };
```

## step2: [browserslist/index.js#L189](https://github.com/ai/browserslist/blob/e3e916f663e6bac7504ddc0ceeb5ec37d7c496a8/index.js#L189)

```js
function browserslist (queries, opts) {
  if (typeof opts === 'undefined') opts = { }

  if (!opts.hasOwnProperty('path')) {  // It is false, opts={ path: undefined, env: undefined }                      
    opts.path = path.resolve ? path.resolve('.') : '.'
  }
   
  // when runned here, opts.path is still equal to undefined
}
```

## step3: [browserslist/node.js#L115](https://github.com/ai/browserslist/blob/e3e916f663e6bac7504ddc0ceeb5ec37d7c496a8/node.js#L115)

```js
loadConfig: function loadConfig (opts) {
    if (process.env.BROWSERSLIST) {
      return process.env.BROWSERSLIST
    } else if (opts.config || process.env.BROWSERSLIST_CONFIG) {
      var file = opts.config || process.env.BROWSERSLIST_CONFIG
      if (path.basename(file) === 'package.json') {
        return pickEnv(parsePackage(file), opts)
      } else {
        return pickEnv(module.exports.readConfig(file), opts)
      }
    } else if (opts.path) {    // It is undefined
      return pickEnv(module.exports.findConfig(opts.path), opts)
    } else {
      return undefined       // get it
    }
  }
```

### CODE REVIEW

**Comment by ai** [comment]
I just came from 10 hours flight. So I will check it only tomorrow.

But looks very promising ;).

**Comment by ai** [comment]
The question — maybe we should remove `opts.hasOwnProperty('path')` from Browserslist. Tomorow I will try to remember why I put this complex check.

**Comment by ai** [comment]
You asked really good question! Unfortunately, I think we should fix Browserslist, because this error still will be in other tools which use Browserslist.

Do you want to send PR to Browserslist to save your name in the history?

**Comment by ken1987** [comment]
wow ~ I can try

**Comment by ai** [comment]
Awesome. I am closing this PR and will wait for new PR in Browserslist. Thanks for finding this issue, good work.

**Pull request closed without merging**
