### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TheRusskiy**
So it uses proper English.

### CODE REVIEW

**Comment by ai** [comment]
Thanks. What is your Twitter name to give you credits in release tweet?

**Comment by TheRusskiy** [comment]
@ai 
https://twitter.com/the_russkiy
it's the simplest change though, not sure if it deserves a mention

**Comment by ai** [comment]
Of course, it is deserved 😺

It helps polish the product to looks more professional.

**Comment by ai** [comment]
Released in 9.7.4

**Pull request merged**
