### PR TITLE
[grid-template-areas] Repetitive grid-area declarations

### PR DESCRIPTION
**Pull request by evgeny-petukhov**

### CODE REVIEW

**Comment by ai** [comment]
Awesome! I will merge and release it tomorrow.

**Comment by evgeny-petukhov** [comment]
It was incredibly fast, less than a minute 😀
Thank you!

**Comment by ai** [comment]
Sorry, release will be delayed until https://github.com/facebook/jest/pull/5489 release

**Comment by ai** [comment]
Released in 7.2.6.

**Pull request merged**
