### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by sigerello**
It's time to update deps, especially ```browserslist``` package because of it's [#161](https://github.com/ai/browserslist/pull/161) fix.

### CODE REVIEW

**Comment by ai** [comment]
You missed that it is `yarn` project. You must update `yarn.lock` as well.

Use:

```
yarn upgrade-interactive
yarn upgrade
yarn test
```

**Comment by ai** [comment]
I will close this PR, because you need to call `yarn upgrade-interactive` on origin `package.json`

**Comment by sigerello** [comment]
I've added yarn.lock in a 2nd commit

**Comment by ai** [comment]
It will be better to do it in fresh fork by:

```
yarn upgrade-interactive
yarn upgrade
yarn test
```

`yarn` should change `package.json`

**Comment by sigerello** [comment]
Ok, I'll made a new PR.

**Comment by sigerello** [comment]
Here it is #867

**Pull request closed without merging**
