### PR TITLE
[grid-area] fix sequence of breakpoints

### LINKED ISSUE #1085: CSS Grid - Sequence of Breakpoints
Another error. I process a grid using two breakpoints, that is, three grid templates. 

The order is No Breakpoint > from 768px > 960px. 

If Autoprefixer now creates the fallbacks for Internet Explorer, the order of the breakpoints does not match. 

```scss
.c-footerNav {
  display: grid;
  grid-gap: 30px 0;
  grid-template:
    "fnbox1" auto
    "fnbox2" auto
    "fnbox3" auto
    "fnbox4" auto /
     1fr;

  @include break('m') {
    grid-gap: 40px;
    grid-template:
      "fnbox1 fnbox1 fnbox1" auto
      "fnbox2 fnbox3 fnbox4" auto /
       1fr  1fr  1fr
  }

  @include break('ml') {
    grid-gap: 60px 40px;
    grid-template:
      "fnbox1 fnbox2 fnbox3 fnbox4" auto /
       1fr  1fr  1fr  1fr;
  }
  &__box1 {
    grid-area: fnbox1;
  }
  &__box2 {
    grid-area: fnbox2;
  }
  &__box3 {
    grid-area: fnbox3;
  }
  &__box4 {
    grid-area: fnbox4;
  }
}
```

Output

```css
.c-footerNav {
  display: -ms-grid;
  display: grid;
  grid-gap: 30px 0;
  -ms-grid-rows: auto 30px auto 30px auto 30px auto;
  -ms-grid-columns: 1fr;
  grid-template: "fnbox1" auto "fnbox2" auto "fnbox3" auto "fnbox4" auto / 1fr;
}

@media screen and (min-width: 768px) {
  .c-footerNav {
    grid-gap: 40px;
    -ms-grid-rows: auto 40px auto;
    -ms-grid-columns: 1fr 40px 1fr 40px 1fr;
    grid-template: "fnbox1 fnbox1 fnbox1" auto "fnbox2 fnbox3 fnbox4" auto / 1fr 1fr 1fr;
  }
}

@media screen and (min-width: 960px) {
  .c-footerNav {
    grid-gap: 60px 40px;
    -ms-grid-rows: auto;
    -ms-grid-columns: 1fr 40px 1fr 40px 1fr 40px 1fr;
    grid-template: "fnbox1 fnbox2 fnbox3 fnbox4" auto / 1fr 1fr 1fr 1fr;
  }
}

.c-footerNav__box1 {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: fnbox1;
}

.c-footerNav__box2 {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: fnbox2;
}

.c-footerNav__box3 {
  -ms-grid-row: 5;
  -ms-grid-column: 1;
  grid-area: fnbox3;
}

.c-footerNav__box4 {
  -ms-grid-row: 7;
  -ms-grid-column: 1;
  grid-area: fnbox4;
}

@media screen and (min-width: 960px) {
  .c-footerNav__box1 {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .c-footerNav__box2 {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  .c-footerNav__box3 {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  .c-footerNav__box4 {
    -ms-grid-row: 1;
    -ms-grid-column: 7;
  }
}

@media screen and (min-width: 768px) {
  .c-footerNav__box1 {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    -ms-grid-column-span: 5;
  }
  .c-footerNav__box2 {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .c-footerNav__box3 {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
  .c-footerNav__box4 {
    -ms-grid-row: 3;
    -ms-grid-column: 5;
  }
}
```

What else struck me, the grid area names don't seem to be scoped. If I use "box1" several times as grid area name in various grids, the autoprefixer will no longer create fallbacks for subsequent grids.

### PR DESCRIPTION
**Pull request by bogdan0083**
This PR fixes #1085

The logic of this fix is simple:
* As the rules being packed into a single the media rule (1), check the closest rule down below. If it's a media rule (2) and it contains the same selectors - insert (1) after (2).

You can check out  the test cases to review is everything ok with the order.

Thanks! :)

### CODE REVIEW

**Comment by ai** [comment]
@Dan503 can I ask you to review it?

**Comment by Dan503** [comment]
The media queries look to me like they are behaving as they are supposed to in the test case file.

I'm happy :)

**Comment by ai** [comment]
I will released it on next `caniuse-db` release to fix also https://github.com/ai/autoprefixer-rails/issues/139

**Comment by ai** [comment]
Released in 9.1.1

**Pull request merged**
