### PR TITLE
[css-grid] fix bug when searching areas

### PR DESCRIPTION
**Pull request by bogdan0083**
PR should fix this issue:  #1096 

@gisu Can you please try this forked version of autoprefixer to make sure the bug is fixed? You can install it like this:

```npm i --save-dev bogdan0083/autoprefixer#add-span-fix```

If the bug is fixed and everything is fine then we can merge :smile:

### CODE REVIEW

**Comment by Dan503** [comment]
You should be able to leave off the `-g`. That's the "global" flag :/

**Comment by bogdan0083** [comment]
Whoops, you right :)

**Comment by gisu** [comment]
Well, I installed it, but it throws errors. I can't say exactly why, because the project I'm trying is quite complex (vue, webpack, gulp, tailwind). 

```bash
events.js:165
      throw er; // Unhandled 'error' event
      ^
Error: Loading PostCSS Plugin failed: Unexpected token =

(@/Users/saschafuchs/Develop/private/gastrocard/site/postcss.config.js)
    at load (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/gulp-postcss/node_modules/postcss-load-config/src/plugins.js:27:13)
    at Object.keys.filter.map (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/gulp-postcss/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/gulp-postcss/node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/gulp-postcss/node_modules/postcss-load-config/src/index.js:72:18)
    at <anonymous>
Emitted 'error' event at:
    at Transform.onerror (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:180:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:453:5)
    at Transform.afterTransform (_stream_transform.js:89:3)
    at Immediate.<anonymous> (/Users/saschafuchs/Develop/private/gastrocard/site/node_modules/gulp-postcss/index.js:93:9)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

`gulp-postcss` I reloaded for test purposes has not changed. I also disabled Autoprefixer to see if it is due to Gulp-PostCSS, then everything runs without errors. I'm testing this again on a fresh project.

**Comment by gisu** [comment]
Tested with a fresh project. Unfortunately, the same problem.

```bash
/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/autoprefixer/lib/transition.js:6
    props = ['transition', 'transition-property'];
          ^

SyntaxError: Unexpected token =
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Module._compile (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at newLoader (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/pirates/lib/index.js:88:7)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
Emitted 'error' event at:
    at /Users/saschafuchs/Develop/private/prefixerKittn/node_modules/gulp-stylelint/dist/index.js:188:15
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

**Comment by bogdan0083** [comment]
@ai how should we handle this PR? I reproduced the bug and fixed it but @gisu can't seem to test it on his project (installed fork outputs errors of some sort, I don't know why)

**Comment by gisu** [comment]
Here is the testing Repo https://github.com/gisu/autoprefixer-test 

```bash
yarn
npm run dev
```

Starts the Testserver. The sass file `src/style/application/components/_testgrid.scss`

**Comment by bogdan0083** [comment]
@gisu Alright, I finally figured out how we can test this PR (stupid but quick way):

1. Clone my branch:
```git clone https://github.com/bogdan0083/autoprefixer.git -b add-span-fix```

2. Go to the folder of cloned repo and run ```yarn``` and then ```gulp``` (if it says that gulp is not installed run ```npm i -g gulp-cli```

3. Take the contents of ```build``` folder of cloned repo and paste to ```${yourProjectFolder}/node_modules/autoprefixer/```

Now it should compile just fine. I tried to compile the test case from your issue and here's the result (with cssnano disabled):

<details>
 <summary>Before</summary>

```css
.container {
  &__inner {
    display: grid;
    grid-gap: 0;
    grid-template:
      'oct log qu1 qu1 qu1' 65px
      'slo slo slo slo slo' auto /
        65px 65px 1fr 1fr 1fr;

    @include break('m') {
      grid-gap: 10px 20px;
      grid-template:
        'log met qu2' 20px
        'log lin lin' auto
        'log nav nav' auto /
          200px 1fr 110px;
    }

    @include break('l') {
      grid-gap: 10px 50px;
      grid-template:
        'log met soc' 20px
        'log lin lin' auto
        'log nav qu2' auto /
        290px 1fr 110px;
    }
  }

  &__log { grid-area: log; }

  &__met { grid-area: met; }

  .c-pageSlogan { grid-area: slo; }

  &__lin { grid-area: lin; }

  .c-offCanvasTrigger {
    grid-area: oct;
    @include break('m') {
      display: none;
    }
  }

  .c-quicklinksMobile {
    grid-area: qu1;
    @include break('m') {
      display: none;
    }
  }

  .c-quicklinksDesktop {
    display: none;
    grid-area: qu2;
    @include break('m') {
      display: flex;
    }
  }

  .c-mainnav {
    display: none;
    grid-area: nav;
    @include break('m') {
      display: block;
    }
  }

  .c-socialNetworks {
    display: none;
    grid-area: soc;
    @include break('l') {
      display: flex;
    }
  }
}

```
</details>
<details>
 <summary>After</summary>

```css
.container__inner {
  display: -ms-grid;
  display: grid;
  grid-gap: 0;
  -ms-grid-rows: 65px 0 auto;
  -ms-grid-columns: 65px 0 65px 0 1fr 0 1fr 0 1fr;
  grid-template: 'oct log qu1 qu1 qu1' 65px 'slo slo slo slo slo' auto / 65px 65px 1fr 1fr 1fr; }
  @media screen and (min-width: 768px) {
    .container__inner {
      grid-gap: 10px 20px;
      -ms-grid-rows: 20px 10px auto 10px auto;
      -ms-grid-columns: 200px 20px 1fr 20px 110px;
      grid-template: 'log met qu2' 20px 'log lin lin' auto 'log nav nav' auto / 200px 1fr 110px; } }
  @media screen and (min-width: 1180px) {
    .container__inner {
      grid-gap: 10px 50px;
      -ms-grid-rows: 20px 10px auto 10px auto;
      -ms-grid-columns: 290px 50px 1fr 50px 110px;
      grid-template: 'log met soc' 20px 'log lin lin' auto 'log nav qu2' auto / 290px 1fr 110px; } }

.container__log {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: log; }

.container__met {
  grid-area: met; }

.container .c-pageSlogan {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  -ms-grid-column-span: 9;
  grid-area: slo; }

.container__lin {
  grid-area: lin; }

.container .c-offCanvasTrigger {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: oct; }
  @media screen and (min-width: 768px) {
    .container .c-offCanvasTrigger {
      display: none; } }

.container .c-quicklinksMobile {
  -ms-grid-row: 1;
  -ms-grid-column: 5;
  -ms-grid-column-span: 5;
  grid-area: qu1; }
  @media screen and (min-width: 768px) {
    .container .c-quicklinksMobile {
      display: none; } }

.container .c-quicklinksDesktop {
  display: none;
  grid-area: qu2; }
  @media screen and (min-width: 768px) {
    .container .c-quicklinksDesktop {
      display: flex; } }

.container .c-mainnav {
  display: none;
  grid-area: nav; }

@media screen and (min-width: 768px) {
    .container__log {
    -ms-grid-row: 1;
    -ms-grid-row-span: 5;
    -ms-grid-column: 1; }
    .container__met {
    -ms-grid-row: 1;
    -ms-grid-column: 3; }
    .container__lin {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
    -ms-grid-column-span: 3; }
    .container .c-quicklinksDesktop {
    -ms-grid-row: 1;
    -ms-grid-column: 5; }
    .container .c-mainnav {
    -ms-grid-row: 5;
    -ms-grid-column: 3;
    -ms-grid-column-span: 3; } }
  @media screen and (min-width: 768px) {
    .container .c-mainnav {
      display: block; } }

.container .c-socialNetworks {
  display: none;
  grid-area: soc; }

@media screen and (min-width: 1180px) {
    .container__log {
    -ms-grid-row: 1;
    -ms-grid-row-span: 5;
    -ms-grid-column: 1; }
    .container__met {
    -ms-grid-row: 1;
    -ms-grid-column: 3; }
    .container__lin {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
    -ms-grid-column-span: 3; }
    .container .c-quicklinksDesktop {
    -ms-grid-row: 5;
    -ms-grid-column: 5; }
    .container .c-mainnav {
    -ms-grid-row: 5;
    -ms-grid-column: 3;
    -ms-grid-column-span: 1; }
    .container .c-socialNetworks {
    -ms-grid-row: 1;
    -ms-grid-column: 5; } }
  @media screen and (min-width: 1180px) {
    .container .c-socialNetworks {
      display: flex; } }

```
</details>

**Comment by Dan503** [comment]
@bogdan0083 I've noticed that you tend to try and commit everything into single big commits with a generic "fixes X" commit message.

Please read this short article on how to write good commits.
https://dev.to/sublimegeek/do-your-commits-pass-this-simple-test-4ak2

Improving your commits will make reviews a bit easier and it will also make your life in general a bit easier if you ever need to revert something.

**Comment by ai** [comment]
It is a good advice in general, but not a problem for Autoprefixer, since I anyway review only full PR diff and merge all commits in one with PR title in commit message.

**Comment by Dan503** [comment]
One of the things the article misses is commit format

```
Short title saying what commit does

Long description with as many characters as you want explaining *why* this commit was needed.
```

The long description isn't always necessary, especially if you point to an issue in an issue tracker, but it's a good practice to get into.

This is more just general life advice.

**Comment by gisu** [comment]
@bogdan0083 I tried it with Nuxt, everything works with the fallbacks. So the order of the breakpoints fits and the reset of the spans. It's all about Webpack.

With my other repo, I can't get it to work. Deleted and updated all node modules. Every time after compiling, it aborts. 

```bash
events.js:165
      throw er; // Unhandled 'error' event
      ^
Error: Loading PostCSS Plugin failed: Unexpected token =

(@/Users/saschafuchs/Develop/private/prefixerKittn/postcss.config.js)
    at load (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/postcss-load-config/src/plugins.js:27:13)
    at Object.keys.filter.map (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/postcss-load-config/src/index.js:72:18)
    at <anonymous>
Emitted 'error' event at:
    at Transform.onerror (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Transform.emit (events.js:180:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:453:5)
    at Transform.afterTransform (_stream_transform.js:89:3)
    at Immediate.<anonymous> (/Users/saschafuchs/Develop/private/prefixerKittn/node_modules/gulp-postcss/index.js:93:9)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prefixerkittn@0.0.1 dev: `cross-env NODE_ENV=development gulp`
npm ERR! Exit status 1
npm ERR! 
```

Why that's the case I don't know. I disabled all the Linters, took everything out of Sass Task except PostCSS. The only PostCSS plugin that runs is the autoprefixer. 
The Error remains. I set back to 9.0.1. everything runs without problems. 

I have already tested nodeversions (9 and 10).

In the other larger project, the error is also displayed more specifically. Several times. 

```js
// lib/transition.js form 
class Transition {
    props = ['transition', 'transition-property']; // <<<<< Here is the token
```

Below again the transition.js of the autoprefixer 9.0.1 for comparison.

```js
function Transition(prefixes) {
    _classCallCheck(this, Transition);

    Object.defineProperty(this, 'props', {
      enumerable: true,
      writable: true,
      value: ['transition', 'transition-property']
    });

    this.prefixes = prefixes;
  }
```

I hope I'm not getting on your nerves too much.

**Comment by gisu** [comment]
@bogdan0083 I have now added this manually to the project, works just like you said. 

Good work :)

**Comment by ai** [comment]
Released in 9.1.1

**Pull request merged**
