### PR TITLE
Upload coverage metrics to Codecov

### PR DESCRIPTION
**Pull request by thomasrockhu**
Hi, Tom from [Codecov](https://codecov.io) here. 

I noticed this repository, and I thought it would be useful to add more useful code coverage metrics to this repository. [Codecov](https://codecov.io) is a hosted code coverage provider with awesome features. You can checkout your first reports [here](https://codecov.io/gh/thomasrockhu/autoprefixer).

I would love all the feedback you have, and please don't hesitate to reach out.

Cheers,
Tom

Codecov ❤️'s open source and will be free forever for OSS

### CODE REVIEW

**Comment by ai** [comment]
Hi. Thanks for the PR.

What will be benefits compare to `jest --coverage`?

**Comment by thomasrockhu** [comment]
Hi @ai, sorry about the delay here, and happy to do the PR.

`jest --coverage` is amazing, and we actually use its output as our input. Codecov takes the coverage report and outputs it into a pull request as a comment so that reviewers and the developer can see the coverage changes. You can also block pull requests via status check if it doesn't have enough test coverage. Both of these features are customizable to what makes sense for your project.

Let me know if that makes sense or if I can answer any other questions.

**Comment by ai** [comment]
Sorry, I do not see any benefits for me.

1. I already have a coverage test.
2. CI will already fall on lever coverage
3. The current output is not so beautiful, but CI falling because of the coverage is a very rare case for this project

Adding any extra service is not “free” for me, because I will need to maintain it, update settings, solve problems, etc. For instance, in this PR you added Coverage install script to the wrong Node.js version. We are running coverage only on the latest Node.js. So I need to fix the script.

Also, I am not a big fan of clouds nowadays.

**Comment by thomasrockhu** [comment]
Hi @ai, really appreciate your feedback here, and your reasoning makes sense to me. If you ever change your mind, I'd be happy to help however I can. Thank you for doing such an incredible job with maintenance across this organization, our team loves `postcss`

**Pull request closed without merging**
