### PR TITLE
[grid-template] fix adding grid span for IE (fixes #1084)

### LINKED ISSUE #1084: Grid Column / Row Span for IE11
The autoprefixer has slight problems with changing the column widths. 

Example a grid with three columns. In the first breakpoint, an element has 2 columns. 

```scss
grid-gap: 10px 20px;
grid-template:
  "log met qu2" 20px
  "log lin lin" auto
  "log nav nav" auto /
  200px 1fr 110px;
```

In the next breakpoint, the element `nav` should now work on a column.

```scss
grid-gap: 10px 50px;
grid-template:
  "log met soc" 20px
  "log lin lin" auto
  "log nav qu2" auto /
  290px 1fr 110px;
```

The problem here is that in the second grid I have `-ms-grid-column-span: 3` still from the previous breakpoint. Which means that the elements now overlap. I have now helped me manually add `-ms-grid-column-span: 1` at the breakpoint.

To automate the whole thing, the autoprefixer should always note `-ms-grid-column-span`, even if the box is only one column wide to overwrite old values in CSS. This also applies to the `-ms-grid-row-span`.

### PR DESCRIPTION
**Pull request by bogdan0083**
This PR fixes #1084.

@Dan503 Can you please review grid-template.out.css in you spare time? I think now it should add -ms-grid-(row|column)-span just fine 👍

### CODE REVIEW

**Comment by Dan503** [comment]
I don't really like the idea of always outputting grid-column/row-span values, but I can also see that trying to pick and choose when to output the span value is going to be a nightmare.

If we go down the always-output-a-span-value route, then I think there is an issue in your pull request. Your span output seems to be inconsistent.

Current output:

```css
    .head {
        -ms-grid-row: 1;
        -ms-grid-column: 1;
        -ms-grid-column-span: 1;
    }
    .nav {
        -ms-grid-row: 2;
        -ms-grid-row-span: 1;
        -ms-grid-column: 1;
    }
```

expected output:
```css
    .head {
        -ms-grid-row: 1;
        -ms-grid-row-span: 1; /* added row span */
        -ms-grid-column: 1;
        -ms-grid-column-span: 1;
    }
    .nav {
        -ms-grid-row: 2;
        -ms-grid-row-span: 1;
        -ms-grid-column: 1;
        -ms-grid-column-span: 1; /* added column span */
    }
```

Basically when grid-areas are being used, Autoprefixer should always output:
- `-ms-grid-row`
- `-ms-grid-row-span`
- `-ms-grid-column`
- `-ms-grid-column-span`

Or is there some smart discrimination going on in your code that is purposely leaving the extra span values out?

**Comment by bogdan0083** [comment]
>  Or is there some smart discrimination going on in your code that is purposely leaving the extra span values out?

Actually there is :). The logic is simple:

If we find grid-template(-area) inside media rule, search the rule above with the same selector and compare -ms-grid-row/column-span values. If values differ then we can add property.  

Before I started working on this issue there was a simple condition that didn't add -ms-grid-row/column-span if one of the values was 1 (e.g ```-ms-grid-row-span: 1```)

> Basically when grid-areas are being used, Autoprefixer should always output:
> -ms-grid-row
> -ms-grid-row-span
> -ms-grid-column
> -ms-grid-column-span

This is very easy to implement actually. The question is: should we add -ms-grid-row/column-span for EVERY rule with grid-template(-areas) or only for the rules inside media rule? (right now it doesn't add property if -ms-grid-row/column-span is 1)

**Comment by Dan503** [comment]
> This is very easy to implement actually.

Nah I prefer keeping the Autoprefixer output as slim as possible. I made that suggestion thinking you might have missed something.

If you have logic to only add the span values when needed then that is a much better solution :)

**Comment by bogdan0083** [comment]
> If you have logic to only add the span values when needed then that is a much better solution :) 

Alright! :smile: So we can now go for a code review I guess :)

**Comment by Dan503** [comment]
You should look into the Travis CLI issues. @ai isn't going to accept the pull request with Travis CLI errors in it.

**Comment by ai** [comment]
Yeap, you need improve tests, so all code should be executed durting test.

Just run `npx jest --coverage` and then check HTML page in `coverage/`

**Comment by bogdan0083** [comment]
@ai Alright, sorry. Now all checks are fine I guess.

**Comment by ai** [comment]
@bogdan0083 thanks! great work

**Comment by ai** [comment]
Sorry, I will take few days to fix this issue https://github.com/postcss/autoprefixer/issues/1081 and release they all together

**Comment by ai** [comment]
Released in 9.1

**Pull request merged**
