### PR TITLE
Add partial support of grid-area

### PR DESCRIPTION
**Pull request by sergey-tyan**
Can not pass 'removes unnecessary prefixes' test. Please suggest how it can be fixed.

### CODE REVIEW

**Comment by ai** [comment]
Tests fall. Seems like you fix can’t clean own prefixes. In this case, you can create separated test case just for `grid-area` and do not use this tests in `removes unnecessary prefixes`.

**Comment by ai** [comment]
Sorry, this PR fixed tests first https://github.com/postcss/autoprefixer/pull/938

But you will be mentioned in ChangeLog as well.

**Comment by sergey-tyan** [comment]
It's ok. #938 even covered more cases. Anyway, it was my first open-source experience and I felt really satisfied when I figured out how some of the inner API works and almost all tests became green :)

**Comment by ai** [comment]
It was really good PR for first open source. Really complex task.

**Pull request closed without merging**
