### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jsw0528**
https://www.alipay.com/

### CODE REVIEW

**Comment by ai** [comment]
Awesome! Do you have link (maybe in Chinese), when Alipay recommends Autoprefixer?

**Comment by ai** [comment]
Maybe we can join Taobao and Alibay and just write “Alibaba”?

**Comment by jsw0528** [comment]
Good idea.

**Comment by jsw0528** [comment]
Oh~ no, Alipay is not in Alibaba Group.

Alipay is in Ant Group: http://www.antgroup.com/

**Comment by ai** [comment]
:(. problem is that 3 companies make too long sentence and it is look not so solid.

**Comment by jsw0528** [comment]
hahahahahaha~ ok.

**Pull request closed without merging**
