### PR TITLE
Add waring to align/justify-items in IE

### PR DESCRIPTION
**Pull request by janczer**
Fix #1123

### CODE REVIEW

**Comment by ai** [comment]
Did you show this warning only if IE is selected in Browserslist 😏

**Comment by janczer** [comment]
I think I don't. Can you please tell me where I can check if IE is selected?

**Comment by ai** [comment]
I am right now on conference. Check other Grid warnings.

**Comment by janczer** [comment]
@Dan503 I added a tips and a test to almost all properties. But unfortunatly I found the bug #1127 and I cannot add to `grid.css` propertie `align-content`  because two tests are conflicts.

**Comment by janczer** [comment]
@Dan503 I added a tips and a test to almost all properties. Thanks for your descriptions.
But unfortunatly I found the bug #1127 and I cannot add to `grid.css` propertie `align-content`  because two tests are conflicts.

@ai I was trying to find how I can add warning if specific browser is add, but I'm failing. When you will have some time, can you please describe me how I can do it? Thanks

**Comment by ai** [comment]
How to check IE is here:
https://github.com/postcss/autoprefixer/blob/master/lib/processor.js#L101

Just increase size limit

**Comment by ai** [comment]
```js
let grid = this.prefixes.add['grid-area']
if (this.prefixes.options.grid && grid) {
```

**Comment by Dan503** [comment]
I'm making some alterations to it and I'll submit it as a pull request against your branch.

**Comment by Dan503** [comment]
> let grid = this.prefixes.add['grid-area']
> if (this.prefixes.options.grid && grid) {

@ai was that for testing if the declaration is in a grid element?

**Comment by ai** [comment]
@Dan503 it tests that we have a browsers which needs Grid prefixes

**Comment by janczer** [comment]
@Dan503 Looks like your commits affected the old tests. Can you check it?

**Comment by Dan503** [comment]
Yeah `autoprefixer.test.js` needs updating to match the new output. I'm not sure how to generate the result to match it to.

I mentioned that in the pull request.

**Comment by ai** [comment]
@Dan503 only by hands 😅

**Comment by janczer** [comment]
I fixed the tests in the last commit. But I have to remove some rules about grid. Is it correct?

cc @ai @Dan503

**Comment by Dan503** [comment]
> only by hands 😅

@ai how do you know what line number and character number the test is looking for then? Those are incredibly difficult to figure out manually.

> Is it correct?

Not at all.

1. You can't remove any of the `auto` stuff
2. The `align/justify-items` warnings need to remain multi-line. It's too hard to read otherwise.
3. Why did you remove the `.warn_ie_align_content` test?

For testing multi-line, you can replicate a new line by using `\n`.

```
This is line one
  This is line 2
```
=
```
"This is line one\n  This is line 2"
```
I recommend reverting that last commit completely and trying again.

**Comment by ai** [comment]
Sorry, I am drunk after a conference 😄😄😄

Will answer in next few days

**Comment by janczer** [comment]
> @ai how do you know what line number and character number the test is looking for then? Those are incredibly difficult to figure out manually.

You can just run the test and check what exactly line has warning.

> @janczer Not at all.
> 
>     1. You can't remove any of the `auto` stuff

Ok, looks like it's problem with code that you added.

>     2. The `align/justify-items` warnings need to remain multi-line. It's too hard to read otherwise.

Autoprefixer has no warnings with new line. I think we can just change warning style.

>     3. Why did you remove the `.warn_ie_align_content` test?

Because here is a bug #1127.

> I recommend reverting that last commit completely and trying again.

Looks like that problem with your commits, can you check it? Or I just revert it.

**Comment by Dan503** [comment]
> You can just run the test and check what exactly line has warning.

Ahh right I get it now, it refers to the line numbers in `test\cases\grid.css`

>  looks like it's problem with code that you added.

I think I might figured out what the main problem was but I'm still getting these weird test fails even though they look like they match up perfectly. Does anyone have any idea what is going on here?

non-sensical-test-fails

> Autoprefixer has no warnings with new line.

There was a multi-line warning at one point 😕 I can't remember what the multi-line warning was for though. @ai @bogdan0083  Did you change it to a single line warning or remove it?

It would be a lot nicer if the warning could stay multi-line.

> Because here is a bug

It looks like it's just a case of the rules being inconsistent. Since we write the test output manually I don't see why the rule can't be included. It just means that that particular rule has its properties the other way around.

When I tried to replicate it using the playground it didn't seem to have that issue. I needed to set the playground to "last 5 version" to get it to output the prefixes.

**Comment by Dan503** [comment]
> Try to remove the indentation and indent the lines by hand. It might be tabs/spaces problem 🤔.

Nope :(

> Yep, I removed it as we no longer needed warnings for multiple area names.

Ahh ok, yeah that makes sense.

**Comment by Dan503** [comment]
@bogdan0083 if you want to take a look at the error, you will find it on my `feature/align-justify-grid-warning` branch.

**Comment by bogdan0083** [comment]
Thanks! Just wanted to ask 😀

**Comment by janczer** [comment]
@ai @bogdan0083 @Dan503 In the latest commit I fixed all test. Can we merge it now? Or I should change it?

**Comment by Dan503** [comment]
Well yeah... you fixed the errors but you did it by removing important functionality. You also got rid of the multi-line aspect. So no, we aren't merging yet.

I created a pull request against your branch with some updates but it has test errors in it. That's what we are figuring out now.

**Comment by janczer** [comment]
> you fixed the errors but you did it by removing important functionality

What exactly functionality you mean? Can you please explain it here and I can add it.

> I created a pull request against your branch with some updates but it has test errors in it.

I'm sorry. But you should fix your pull request.

**Comment by Dan503** [comment]
> What exactly functionality you mean?

You removed all the warnings that Autoprefixer produces when people try to use grid `auto` properties like `grid-auto-rows`.

**Comment by bogdan0083** [comment]
> Try to remove the indentation and indent the lines by hand. It might be tabs/spaces problem 🤔.
> Nope :(

I've just checked your branch and I have no strange errors 🤔

**Comment by Dan503** [comment]
Really? so you run `npm run test` and it came back with zero errors?

**Comment by janczer** [comment]
> You removed all the warnings that Autoprefixer produces when people try to use grid auto properties like grid-auto-rows.

It's not true. You can see it in the last commit: [25ba8a2](https://github.com/postcss/autoprefixer/commit/25ba8a2e6312c2a470cf1c72b99d7359b7d7c357)

**Comment by Dan503** [comment]
Oh... sorry, yeah looks like it was altered rather than removed.

I still think the multi-line aspect is important though.

**Comment by bogdan0083** [comment]
> Really? so you run npm run test and it came back with zero errors?

I have one error about the warning message, one about selector namings of this sort:
```
    - .warn_ei_align {
    + .warn_ie_align {
```

and one more: 
```
      .warn_ie_align_content {
    +   -ms-flex-line-pack: center;
        -webkit-align-content: center;
    -   -ms-flex-line-pack: center;
        align-content: center;
        display: -ms-grid;
        display: grid;
      }
```

**Comment by janczer** [comment]
@bogdan0083 the second one related to #1127

**Comment by Dan503** [comment]
Ah ok, I'll fix up those 2 errors. My console is drowned in bogus errors for whatever reason so I couldn't see them.

**Comment by Dan503** [comment]
@bogdan0083 I've pushed theoretical fixes for those 2 issues. Can you test?

**Comment by bogdan0083** [comment]
the first is 
```
has disabled grid options by default
```
and the second is
```
supports grid layout
```

**Comment by bogdan0083** [comment]
Did you try to remove the fork and set it up again and then use some other editor? I don't know, something is breaking your tests 🤔

**Comment by Dan503** [comment]
There were other alterations that I made in my version as well in case people were thinking it's not worth the hassle.

- I personalised the warning messages further so that it only mentions the property that the user used rather than all the properties.
- I included `place-*` in the warning message
- I moved the code into the area that the rest of the "grid-must-be-enabled" tests were in.

**Comment by Dan503** [comment]
> If you want to omit those bogus errors you can try to run a single test by using jest -t 'test-name'

Using Jest directly worked 😊

> Did you try to remove the fork and set it up again and then use some other editor?

umm... I didn't try that, I did try deleting `node_modules` and re-intalling though.

**Comment by bogdan0083** [comment]
> Using Jest directly worked 😊
That's cool! Glad it helped.

**Comment by Dan503** [comment]
Ok I'll delete the align-content test. It is more difficult to solve that I was expecting 😕

**Pull request closed without merging**
