### PR TITLE
[grid-gap] Inherit gaps from less specific rules

### LINKED ISSUE #1117: [css-grid] Not inheriting gaps from less specific rules
<details>
    <summary>Input CSS</summary>

```css

.grid {
  display: grid;
  grid-gap: 20px; /* <-- Notice the grid-gap value here */
  grid-template-areas:
    "a b"
    "c d";
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
  /* grid-gap left out but should be inherited from .grid */
  grid-template-areas:
    "e f"
    "g h";
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
    grid-template-areas:
      "a b"
      "c d";
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
    grid-template-areas:
      "e f"
      "g h";
    grid-template-columns: repeat(2, 1fr);
    grid-template-rows: repeat(2, 1fr);
  }
}

.a { grid-area: a; }
.b { grid-area: b; }
.c { grid-area: c; }
.d { grid-area: d; }
.e { grid-area: e; }
.f { grid-area: f; }
.g { grid-area: g; }
.h { grid-area: h; }
```

</details>

<details>
    <summary>Current CSS output</summary>

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-gap: 20px;
      grid-template-areas: "a b"
 "c d";
  -ms-grid-columns: 1fr 20px 1fr;
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
      grid-template-areas: "e f"
 "g h";
  -ms-grid-columns: (1fr)[2];  /* <-- no grid-gap inheritance */
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: (1fr)[2];  /* <-- no grid-gap inheritance */
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
        grid-template-areas: "a b"
 "c d";
    -ms-grid-columns: 1fr 20px 1fr;
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
        grid-template-areas: "e f"
 "g h";
    -ms-grid-columns: (1fr)[2];  /* <-- no grid-gap inheritance */
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: (1fr)[2];  /* <-- no grid-gap inheritance */
    grid-template-rows: repeat(2, 1fr);
  }
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: b;
}

.c {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: c;
}

.d {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: d;
}

@media (max-width: 600px) {
  .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .b {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
  }
  .c {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
  }
  .d {
    -ms-grid-row: 2;
    -ms-grid-column: 2;
  }
}

.e {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: e;
}

.f {
  -ms-grid-row: 1;
  -ms-grid-column: 2;
  grid-area: f;
}

.g {
  -ms-grid-row: 2;
  -ms-grid-column: 1;
  grid-area: g;
}

.h {
  -ms-grid-row: 2;
  -ms-grid-column: 2;
  grid-area: h;
}

@media (max-width: 600px) {
  .e {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .f {
    -ms-grid-row: 1;
    -ms-grid-column: 2;
  }
  .g {
    -ms-grid-row: 2;
    -ms-grid-column: 1;
  }
  .h {
    -ms-grid-row: 2;
    -ms-grid-column: 2;
  }
}
```

</details>

<details>
    <summary>Expected CSS output</summary>

```css
.grid {
  display: -ms-grid;
  display: grid;
  grid-gap: 20px;
      grid-template-areas: "a b"
 "c d";
  -ms-grid-columns: 1fr 20px 1fr;
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;
  grid-template-rows: repeat(2, 1fr);
}

.grid.more-specific {
      grid-template-areas: "e f"
 "g h";
  -ms-grid-columns: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
  grid-template-columns: repeat(2, 1fr);
  -ms-grid-rows: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
  grid-template-rows: repeat(2, 1fr);
}

@media (max-width: 600px) {
  .grid {
        grid-template-areas: "a b"
 "c d";
    -ms-grid-columns: 1fr 20px 1fr;
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;
    grid-template-rows: repeat(2, 1fr);
  }
  .grid.more-specific {
        grid-template-areas: "e f"
 "g h";
    -ms-grid-columns: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
    grid-template-columns: repeat(2, 1fr);
    -ms-grid-rows: 1fr 20px 1fr;  /* <-- grid-gap inheritance */
    grid-template-rows: repeat(2, 1fr);
  }
}

.a {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: a;
}

.b {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: b;
}

.c {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: c;
}

.d {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: d;
}

@media (max-width: 600px) {
  .a {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .b {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  .c {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .d {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
}

.e {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: e;
}

.f {
  -ms-grid-row: 1;
  -ms-grid-column: 3;
  grid-area: f;
}

.g {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: g;
}

.h {
  -ms-grid-row: 3;
  -ms-grid-column: 3;
  grid-area: h;
}

@media (max-width: 600px) {
  .e {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .f {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  .g {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .h {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by bogdan0083**
Fixes #1117

cc @Dan503 

This should work for simple cases. I added rules in the tests as an example, check it out 😀

### CODE REVIEW

**Comment by ai** [comment]
Cool!

**Comment by Dan503** [comment]
Cool 👍 

What happens if you have something like this?

```css
.origin {
  grid-gap: 20px;
  //other styles
}

.parent .origin {
  //no gap setting
}
```

I'm also curious as to what happens when this is applied to duplicate area names. Try running it through the complex duplicate area names example and see what happens.

**Comment by bogdan0083** [comment]
I'll test your suggestions a little later :)

**Comment by Dan503** [comment]
Thanks for starting on a fix for this one 😊

With duplicate area names now supported I think this issue is a bit more obvious now.

**Comment by bogdan0083** [comment]
Alright, I've added a test case with descendant selector, I guess the inheritance works for such cases!

This is what the output of complex case (I'll send only the output):
<details>
<summary>Output</summary>

```css
#main > #content {
  grid-area: content;
}
#main > .sidebar {
  grid-area: first-sb;
}
#main > .sidebar.second {
  grid-area: second-sb;
}
@media (min-width: 660px) {
  #main {
    grid-gap: 45px;
    display: -ms-grid;
    display: grid;
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 45px 1em 45px 1fr 45px 20%;
        grid-template: "..... ... content ....."/20% 1em 1fr 20%;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 45px 1em 45px 300px 45px 30px 45px 1fr 45px 20%;
        grid-template: "..... ... first-sb .... content ....."/20% 1em 300px 30px 1fr 20%;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 45px 1em 45px 1fr 45px 30px 45px 300px 45px 20%;
        grid-template: "..... ... content .... second-sb ....."/20% 1em 1fr 30px 300px 20%;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 45px 1em 45px 200px 45px 30px 45px 1fr 45px 30px 45px 200px 45px 20%;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/20% 1em 200px 30px 1fr 30px 200px 20%;
  }

  /* what the hell? Why grid-column is 5? */
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }

  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 7;
  }
}
@media (max-width: 1499px) {
  #main {
    grid-gap: 60px;
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 1fr 60px 10%;
        grid-template: "..... ... content ....."/10% 1em 1fr 10%;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 250px 60px 30px 60px 1fr 60px 10%;
        grid-template: "..... ... first-sb .... content ....."/10% 1em 250px 30px 1fr 10%;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 1fr 60px 30px 60px 250px 60px 10%;
        grid-template: "..... ... content .... second-sb ....."/10% 1em 1fr 30px 250px 10%;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 200px 60px 30px 60px 1fr 60px 30px 60px 200px 60px 10%;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/10% 1em 200px 30px 1fr 30px 200px 10%;
  }

  /* what the hell? Why grid-column is 5? */
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }

  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 7;
  }
}
@media (max-width: 959px) {
  #main {
    grid-gap: 80px;
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 1fr 80px 2em;
        grid-template: "..... ... content ....."/2em 1em 1fr 2em;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 200px 80px 30px 80px 1fr 80px 2em;
        grid-template: "..... ... first-sb .... content ....."/2em 1em 200px 30px 1fr 2em;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 1fr 80px 30px 80px 200px 80px 2em;
        grid-template: "..... ... content .... second-sb ....."/2em 1em 1fr 30px 200px 2em;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 150px 80px 30px 80px 1fr 80px 30px 80px 150px 80px 2em;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/2em 1em 150px 30px 1fr 30px 150px 2em;
  }

  /* what the hell? Why grid-column is 5? */
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }

  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 3;
  }
  #main.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 7;
  }
}
```
</details>
<br/>

You can see that grid-gap inheritance works, but the output of `#main > .content` is strange:
```css
#main > #content {
  -ms-grid-row: 1;
  -ms-grid-column: 5;
}
```
If I add the `grid-gap` property, the `-ms-grid-column` goes from 3 to 5. I guess we have a bug somewhere 🤔

**Comment by Dan503** [comment]
> If I add the grid-gap property, the -ms-grid-column goes from 3 to 5.

That's not a bug, it's a feature.

Remember, that IE doesn't support `grid-gap` by default. We fake grid-gap support by adding in extra columns.

**Comment by Dan503** [comment]
If you count both the real columns and the gaps between each column then it makes sense.

**Comment by bogdan0083** [comment]
Whoops, sorry. I didn't know that. Now it makes sense 😄

**Comment by Dan503** [comment]
I'm double checking, I'm not 100% sure the column count is right.

**Comment by bogdan0083** [comment]
Yeah, you're right. For some reason Autoprefixer doesn't take into account inherited gap values for grid-area prefixes

**Comment by bogdan0083** [comment]
Yep. I found where the problem is. Will try to fix this

**Comment by bogdan0083** [comment]
<details>
<summary>Output</summary>

```css
#main > #content {
  grid-area: content;
}
#main > .sidebar {
  grid-area: first-sb;
}
#main > .sidebar.second {
  grid-area: second-sb;
}
@media (min-width: 660px) {
  #main {
    grid-gap: 40px;
    display: -ms-grid;
    display: grid;
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 40px 1em 40px 1fr 40px 20%;
        grid-template: "..... ... content ....."/20% 1em 1fr 20%;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 40px 1em 40px 300px 40px 30px 40px 1fr 40px 20%;
        grid-template: "..... ... first-sb .... content ....."/20% 1em 300px 30px 1fr 20%;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 40px 1em 40px 1fr 40px 30px 40px 300px 40px 20%;
        grid-template: "..... ... content .... second-sb ....."/20% 1em 1fr 30px 300px 20%;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 20% 40px 1em 40px 200px 40px 30px 40px 1fr 40px 30px 40px 200px 40px 20%;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/20% 1em 200px 30px 1fr 30px 200px 20%;
  }
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 13;
  }
}
@media (max-width: 1499px) {
  #main {
    grid-gap: 60px;
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 1fr 60px 10%;
        grid-template: "..... ... content ....."/10% 1em 1fr 10%;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 250px 60px 30px 60px 1fr 60px 10%;
        grid-template: "..... ... first-sb .... content ....."/10% 1em 250px 30px 1fr 10%;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 1fr 60px 30px 60px 250px 60px 10%;
        grid-template: "..... ... content .... second-sb ....."/10% 1em 1fr 30px 250px 10%;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 10% 60px 1em 60px 200px 60px 30px 60px 1fr 60px 30px 60px 200px 60px 10%;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/10% 1em 200px 30px 1fr 30px 200px 10%;
  }
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-first-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 13;
  }
}
@media (max-width: 959px) {
  #main {
    grid-gap: 80px;
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 1fr 80px 2em;
        grid-template: "..... ... content ....."/2em 1em 1fr 2em;
  }
  #main.has-first-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 200px 80px 30px 80px 1fr 80px 2em;
        grid-template: "..... ... first-sb .... content ....."/2em 1em 200px 30px 1fr 2em;
  }
  #main.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 1fr 80px 30px 80px 200px 80px 2em;
        grid-template: "..... ... content .... second-sb ....."/2em 1em 1fr 30px 200px 2em;
  }
  #main.has-first-sidebar.has-second-sidebar {
    -ms-grid-rows: auto;
    -ms-grid-columns: 2em 80px 1em 80px 150px 80px 30px 80px 1fr 80px 30px 80px 150px 80px 2em;
        grid-template: "..... ... first-sb .... content .... second-sb ....."/2em 1em 150px 30px 1fr 30px 150px 2em;
  }
  #main > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > #content {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-first-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar {
    -ms-grid-row: 1;
    -ms-grid-column: 5;
  }
  #main.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 9;
  }
  #main.has-first-sidebar.has-second-sidebar > .sidebar.second {
    -ms-grid-row: 1;
    -ms-grid-column: 13;
  }
}

```
</details>

Now the values seem to be fine! 😄

**Comment by Dan503** [comment]
Cool, yeah that looks like it's working :)

Just checking, do these two scenarios act as expected?

```css
.parent .origin {
  grid-gap: 20px;
  /* other styles */
}

.origin {
  /* grid gap should not inherit */
}
```

```css
.origin.one {
  grid-gap: 20px;
  /* other styles */
}

.origin.two {
  /* grid gap should not inherit */
}
```

**Comment by bogdan0083** [comment]
I added the test cases you described above in the grid-gap.css, you can check the output (I also added comments to make it more clear)

**Comment by Dan503** [comment]
One more type to make sure is working properly.

```css
.grid.one {
  grid-gap: 20px;
  /* other styles */
}

.grid.two {
  /* grid gap should not inherit */
}
```

I do like that you inherit in this scenario
```css
.grid.one {
  grid-gap: 20px;
  /* other styles */
}

.grid.one.two {
  /* grid gap should inherit */
}
```
What happens if the selector is not identical but functionally the same?
```css
.grid.one.two {
  grid-gap: 20px;
  /* other styles */
}

.grid.two.one {
  /* grid gap should inherit */
}
```

**Comment by bogdan0083** [comment]
Hmm, those two cases wil be harder to implement, I'll see how to approach them

**Comment by Dan503** [comment]
I'm actually wondering if we support that second option in anything. It might be worth leaving it out if it's too difficult.

For the second option to be worth supporting it also needs to be supported in area names.

**Comment by bogdan0083** [comment]
I added test cases, now this should work:
```css
.grid.one {
  grid-gap: 20px;
  /* other styles */
}

.grid.one.two {
  /* grid gap should inherit */
}
```
 
The second case you described is quite complex and I currently have no time to implement it 😞. 

Although I would be happy if you open a new issue about that case (or if you're busy I will create the issue by myself). I plan to work on it someday.

**Comment by Dan503** [comment]
Can you create it? It's midnight where I am. I was about to go to bed 🛌😴

That second one is a pretty minor use case. It's fine if it doesn't get fixed for a while.

**Comment by bogdan0083** [comment]
Sure I will! :)

**Comment by bogdan0083** [comment]
> It will need to wait a couple days for when I'm back at work if we want to do a full production site test... unless someone else has some good test css we can run it through?

i tried a few projects that i found on github and it worked fine. we just need to make sure autoprefixer doesn't crash on big stylesheets.

**Comment by Dan503** [comment]
I've given this a bit of a test in some real sites. It seems to be working great :)

@ai ready for you to review and merge.

**Pull request merged**
